fundamental:
  market_cap_min: 10000000000000
  roe_min: 0.0
  der_max: 2.0
  npm_min: 0.0
liquidity:
  volume_min: 100000000
  value_min: 500000000
momentum:
  price_min: 100
  volume_spike_factor: 2.0
  open_low_tolerance_pct: 0.5
trading:
  sl_pct: -2.0
  tp_pct: 5.0
